# This file controls the settings for your Quarto template
# website settings
website:
  title: "Liu Liu" # Your name
  description: "Ph.D. candidate in Computational Urban Science | MIT" # A brief slogan (optional)
  image: img/my_image.jpg
  favicon: img/favicon.png
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Papers"
        href: papers/index.qmd
      - text: "Visualization"
        href: visualization/index.qmd
      - text: "presentations"
        href: presentations/index.qmd
      - text: "Portfolio"
        href: portfolio/index.qmd
    # your social media handles
    right:
      - text: "{{< iconify fa6-solid building-columns size=LARGE >}}"
        href: https://dusp.mit.edu/people/liu-liu
        aria-label: DUSP

      - text: "{{< iconify fa linkedin size=LARGE >}}"
        href: https://www.linkedin.com/in/liu-liu-08033547/
        aria-label: LinkedIn
        
      - text: "{{< iconify fa-brands github size=LARGE >}}"
        href: https://github.com/lyons66
        aria-label: GitHub
        
      - text: "{{< iconify fa6-brands x-twitter size=LARGE >}}"
        href: https://twitter.com/liuliu_lyons66
        aria-label: X
        
# To find the icons: https://icon-sets.iconify.design/ant-design/zhihu-circle-filled/
  
# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: overlay
  page-footer: 
    left: |
      <span class="container"><strong>Made with [Quarto](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Contact Liu Liu](mailto:mail.lyons66@mit.edu){target="_blank"}</strong></span>
      
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - sandstone
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 300px
      gutter-width: 1.5rem