# This file controls the settings for your Quarto template
# website settings
website:
  title: "Liu Liu" # Your name
  description: "Ph.D. Candidate in Computational Urban Science | MIT" # A brief slogan (optional)
  image: img/my_image.jpg
  favicon: img/favicon.png
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Papers"
        href: papers/index.qmd
      - text: "Portfolio"
        href: portfolio/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: house
        href: https://dusp.mit.edu/people/liu-liu
      - icon: book-fill
        href: https://scholar.google.com/citations?user=D3PSmFsAAAAJ
      - icon: linkedin
        href: https://www.linkedin.com/in/liu-liu-08033547/
      - icon: envelope-fill
        aria-label: email
        href: "mailto:mail.lyons66@mit.edu"  
  
# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    center: |
      <span class="container"><strong>[Contact Deepsha Menghani](mailto:mail.lyons66@mit.edu){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[CV&Resume](https://www.dropbox.com/scl/fo/ghrtsq5to79059lximk01/h?rlkey=cev0uzwgvu4jkus9eo6kkbgn7&dl=0){target="_blank"}</strong></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - sandstone
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true