---
title: "Research papers"
subtitle: "Selected from my Google Scholar profile"
page-layout: full
title-block-banner: "papers_cover.png"
---

```{=html}
<style>
.quarto-title-banner {
  background-position: 50% 55%;
  height: 200px;
}

#quarto-document-content {
  margin-top: 0;
  padding-top: 0;
}

#quarto-margin-sidebar {
  padding-top: 0;
}

</style>
```

Usually I do not update this page frequently. For the most recent publication list, please refer to my [Curriculum Vitae](https://www.dropbox.com/scl/fo/ghrtsq5to79059lximk01/h?rlkey=cev0uzwgvu4jkus9eo6kkbgn7&dl=0) and [Google Scholar](https://scholar.google.com/citations?user=D3PSmFsAAAAJ) profile.

## Peer-Reviewed Papers

- **Sevtsuk, A., Basu, R., Liu, L., Alhassan, A., & Kollar, J.**  
  *NYC Walks: A City-Wide Foot-Traffic Model to Guide Pedestrian-Oriented Planning and Design*  
  Accepted by **Nature Cities**.
  
-	**Liu, Z., Gao, X., Niu, F., Gao, Q., Liu, L., & Piramuthu, R.**
  *START: Spatial and Textual Learning for Chart Understanding*
  Accepted by **WACV 2026**.

- **Liu, L., Kudaeva, A., Cipriano, M., Al Ghannam, F., Tan, F., de Melo, G., & Sevtsuk, A.**  
  *MINGLE: VLMs for Semantically Complex Region Detection*  
  Accepted by **AAAI 2026 – Artificial Intelligence for Social Impact Track**  

- **Kang, Y., Chen, J., Liu, L., Sharma, K., Mazzarello, M., Mora, S., Duarte, F.* (corresp.), & Ratti, C.**  
  *Human vs. AI Safety Perception? Decoding Human Safety Perception with Eye-Tracking Systems, Street-View Images, and Explainable AI*  
  *Computers, Environment & Urban Systems*, (Accepted Manuscript ID CEUS-D-25-00395).  

- **Liu, L., & Andres Sevtsuk**  
  *Clarity or Confusion: A Review of Computer-Vision Street Attributes in Urban Studies and Planning*  
  *Cities*, 150, 105022 (2024).  
  [View](https://doi.org/10.1016/j.cities.2024.105022)  

- **Colaninno, N., Rounaq Basu, Maryam Hosseini, Abdulaziz Alhassan, Liu Liu, & Andres Sevtsuk**  
  *A Sidewalk-Level Urban Heat-Risk Assessment Framework Using Pedestrian Mobility and Urban Micro-climate Modelling*  
  *Environment & Planning B: Urban Analytics and City Science* (2024).  
  [View](https://journals.sagepub.com/doi/full/10.1177/23998083241280746)  

- **Zhou, B., Liu, L., Oliva, A., & Torralba, A.**  
  *Recognizing City Identity via Attribute Analysis of Geo-Tagged Images*  
  *European Conference on Computer Vision* (ECCV 2014), pp. 519-534.  
  [Download](https://link.springer.com/content/pdf/10.1007/978-3-319-10578-9_34.pdf)  

- **Liu, L., Zhou, B., Zhao, J., & Ryan, B. D.**  
  *C-IMAGE: City Cognitive Mapping through Geo-Tagged Photos*  
  *GeoJournal*, 81 (6), 817-861 (2016).  
  [View](https://link.springer.com/article/10.1007/s10708-016-9739-6)  

- **Long, Y., & Liu, L.**  
  *How Green Are the Streets? An Analysis for Central Areas of Chinese Cities Using Tencent Street View*  
  *PLOS ONE*, 12 (2), e0171110 (2017).  
  [Download](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0171110)  

- **Zhang, F., Zhou, B., Liu, L., Liu, Y., Fung, H. H., Lin, H., & Carlo Ratti**  
  *Measuring Human Perceptions of a Large-Scale Urban Region Using Machine Learning*  
  *Landscape and Urban Planning*, 180, 148-160 (2018).  
  [View](https://www.sciencedirect.com/science/article/pii/S0169204618308545)  

- **Liu, L., Zhang, F., Zhou, B., Wang, Z., & Li, Y.**  
  *STREETALK: A Navigation System for Pedestrians and Cyclists*  
  *Landscape Architecture Frontiers* (2018).  
  [Download](https://oversea.cnki.net/knavi/JournalDetail?pcode=CJFD&pykm=jgsj)  

- **Cui, C., et al.**  
  *The Spatial-Temporal Dynamics of Daily Inter-City Mobility in the Yangtze River Delta: An Analysis Using Big Data*  
  *Habitat International* (2020).  
  [View](https://www.sciencedirect.com/science/article/abs/pii/S0197397519311373)  

- **Zhang, D., Yi, H., Chen, Y., Jiang, N., Shao, J., & Liu, L.**  
  *An Urban Infrastructure Assessment System Built on Geo-Tagged Images and Machine Learning*  
  *Computational Urban Science* 2 (1), 1-21 (2022).  
  [Download](https://link.springer.com/article/10.1007/s43762-022-00056-9)  

#### Papers Under Review

- **Zhang, H., Liu, L., Wang, P., & Zhao, J.**  
  *Depicting the Blurred Regional Boundaries in China Using Individual Mobility Data*  
  *Computational Urban Science*, under review (Manuscript ID CUSC-D-25-00097). 

#### Preprint

- **Hosseini, M., Cipriano, M., Eslami, S., Hodczak, D., Liu, L., Sevtsuk, A., & de Melo, G.**  
  *ELSA: Evaluating Localization of Social Activities in Urban Streets*  
  *arXiv* preprint arXiv:2406.01551 (2024).  
  [Download](https://arxiv.org/abs/2406.01551)  

#### Manuscripts Completed (No Submission)

- **Liu, L., Gao, X., Gao, Q., & Piramuthu, R.**  
  *Exploring the Challenges of Humanity’s Last Exam Dataset Analysis, Small Model Evaluation, and Enhancement Trials*  
  Completed during Applied Scientist PhD Internship, Amazon AGI, Sunnyvale CA (2025).  
  [View upon request](https://www.dropbox.com/scl/fi/8eshq8b80b9mmp4c19ukt/Exploring_the_Challenges_of_Humanity_s_Last_Exam.pdf?rlkey=qgvc22lbsc78j86apggtklqpv&st=lvqor1f4&dl=0)
  
- **Liu, L., Gao, X., Gao, Q., & Piramuthu, R.**  
  *ABCxM: A Benchmark for Multimodal Models Playing Scores to Music*  
  Completed during Applied Scientist PhD Internship, Amazon AGI, Sunnyvale CA (2024).  
  Developed the first end-to-end benchmark and evaluation framework for notation-to-music generation.  
  [View upon request](https://www.dropbox.com/scl/fi/07pv6n5h6n8c784nlh4k3/liu-liu_1.pdf?rlkey=sf34mrgrm85cz0wq557vgqq4a&st=jznjgqwt&dl=0)  

- **Liu, L., Gao, X., Gao, Q., & Piramuthu, R.**  
  *VIS: A Benchmark for Foley Models and Visually Indicative Sounds*  
  Completed during Applied Scientist PhD Internship, Amazon AGI, Sunnyvale CA (2024).  
  Created human-annotated, multi-domain datasets for evaluating video-to-audio generation models.  
  [View upon request](https://www.dropbox.com/scl/fi/6idfzeoj59iff4g8wxi69/liu-liu_2.pdf?rlkey=orjuocbjjipuzqjjg6d8ys7yu&st=f6ah28z6&dl=0)


*Additional papers writtern in Chinese are listed in the *[*Curriculum Vitae*](https://www.dropbox.com/scl/fo/ghrtsq5to79059lximk01/h?rlkey=cev0uzwgvu4jkus9eo6kkbgn7&dl=0) *only.*

---

## Service & Grants

-	**Co-Investigator (Subproject PI)**, National Key Research and Development Program of China — “Multi-dimensional Street Quality Enhancement and Coordinated Control Technology Platform Construction” (Subproject: 2023YFC3805305-03, PI: Liu Liu, Suzhou Citory Technology Co., Ltd.), Funding Period: December 2023 – November 2026.
- **Principal Investigator**, “Observing the ‘Sidewalk Ballet’: Leveraging LMMs to Detect Social Interactions in Large-Scale Urban Imagery Datasets,” ACCESS CIS250088 (2025-2026).  
-	**Co-Principal Investigator**, Moments: Leveraging Continuous Visual and Auditory Experiences to Assess Urban Attraction (CIS250360), Advanced Cyberinfrastructure Coordination Ecosystem: Services & Support (ACCESS), Alexandria, VA, US, Funding Period: October 2025 – October 2026 [↗]


- **Reviewer** for *Cities*, *Nature Cities*, *Sustainable Cities & Society*, *Environment & Planning B*, *Journal of Transport and Land Use*, *Transactions in Urban Data, Science, and Technology*, *Annals of the American Association of Geographers*,  *Computational Urban Science*, *Landscape and Urban Planning*, *International Journal of Digital Earth*, and others (20 + reviews).  

