---
title: "VIDEOS of other DEMOS"
subtitle: "Below is a collection of the demo videos of other project I led in past years."
page-layout: full
# title-block-banner: true
title-block-banner: "videos_cover.png"
editor: 
  markdown: 
    wrap: 72
format:
  html:
    toc: true
    toc-depth: 3
    toc-float:
      collapsed: false
      smooth-scroll: true
      sticky: true
---

```{=html}
<style>
.quarto-title-banner {
  background-position: 50% 40%;
  height: 200px;
}

#quarto-document-content {
  margin-top: 0;
  padding-top: 0;
}

#quarto-margin-sidebar {
  padding-top: 0;
}

</style>
```


## Boston Taxi (2011)

This the visualization work based a Boston Taxi data challenge. 

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/DXQkZMXftdY >}}

:::

## Shenzen@pulse (2014)

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/o5hiJueShGs >}}

:::

## Informal vendors in Shanghai (2016)

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/-K40QXviS5o >}}

:::

## Cycling 24h in Shanghai (2017)

This a visualization demo based on user data from Xingzhe shown on the 2017 Bicycle EXPO.

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/XWydp-yi814 >}}

:::

## The interactive screen in Xinhua Book Store (2017)

This is a user interaction screen provided inside a popular bookstore designed by Tadao Ando.

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/bq5B7d6kUyA >}}

:::

## Searching urban patterns worldwide (2017)

A working-on projects for any user who draws some lines to provide best matched satellite images all over the world.

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/FbtfPcLp1Nk >}}

:::

## Aesthetic Evaluation of Shop Signs (2018)

A store sign evaluation and scoring system based on extensive reviews by design professionals.

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/-p7eQLrfLfQ >}}

:::

## Chongqing 24h OD based on cell phone data from China Unicom (2018)

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/Pqe9E_azcJE >}}

:::


## Time contour web APP based on Didi Data(2018)

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/n21XLng565Q >}}

:::

## VGE for Lujiazui (2018)

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/2NCJdfmL4WA >}}

:::

## Population Visualization (2019)

China's population growth from 2001 to 2018 based on LandScan dataset.

::: {layout-ncol="2"}

{{< video https://www.youtube.com/embed/S-w09WldSug >}}

:::


<!-- <div id="toc-container"></div> <!-- Placeholder for TOC -->
